### ISSUE TITLE
Comentarios.

### ISSUE THREAD

**Issue by Eliezer3104** [uETITC/SoftwareDesign-TPC-4-2018#2]
Está bien organizada la estructura de directorios, aunque los nombres de las carpetas no son claros, tambien hace falta el uso de imagenes que ayuden claramente el propósito del proyecto, me gusta que tiene enlaces a documentación adicional o recursos relacionados y por ultimo Se utilizan correctamente ramas para desarrollo, pruebas y producción.

**Comment by saguileran** [comment]
Repositorio equivocado, este es le del curso.
