### ISSUE TITLE
comentario en el manejo de los diagramas 

### ISSUE THREAD

**Issue by michaelorju** [uETITC/SoftwareDesign-TPC-4-2018#4]
buenas noches 
en los diagramas que implementan en los proyectos se ve bn utlizado el esquema pero queda faltando el sistema que se maneja y las bases de datos donde recide la informacion. no por todos pero en unos casos de uso y secuenciales no se ve reflejado.

**Comment by saguileran** [comment]
Repositorio equivocado, este es le del curso.
